version: "3.8"

services:
  api:
    container_name: reportmaker.api
    user: 1000:1000 # for linux to delete created files
    build:
      context: .
      dockerfile: Dockerfile
      target: reportmaker-backend
    command:
      [
        "uvicorn",
        "src.core.main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    restart: unless-stopped
    volumes:
      - .:/reportmaker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: bitnami/postgresql:15
    restart: unless-stopped
    container_name: reportmaker_db
    env_file:
      - .env
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 2s
      retries: 10


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  postgres-data:
