"""

Revision ID: 68d2ebd3afff
Revises: 1fa78a8422c8
Create Date: 2023-08-18 15:35:26.676831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d2ebd3afff'
down_revision = '1fa78a8422c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('patients', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('patients', 'is_relative')
    op.drop_constraint('relationships_patient_id_fkey', 'relationships', type_='foreignkey')
    op.drop_constraint('relationships_relative_id_fkey', 'relationships', type_='foreignkey')
    op.create_foreign_key(None, 'relationships', 'patients', ['relative_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relationships', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.create_foreign_key('relationships_relative_id_fkey', 'relationships', 'patients', ['relative_id'], ['id'])
    op.create_foreign_key('relationships_patient_id_fkey', 'relationships', 'patients', ['patient_id'], ['id'])
    op.add_column('patients', sa.Column('is_relative', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('patients', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
