"""

Revision ID: 1fa78a8422c8
Revises: ed4cc035c329
Create Date: 2023-08-18 12:34:09.933806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa78a8422c8'
down_revision = 'ed4cc035c329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('document_type', sa.Enum('passport', 'birth_certificate_new', 'birth_certificate_old', name='doctype'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('relative_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('father', 'mother', 'grandfather', 'grandmother', 'guardian', name='relationshiptype'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['relative_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'relative_id')
    )
    op.add_column('patients', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.Enum('female', 'male', name='gender'), nullable=True))
    op.add_column('patients', sa.Column('snils', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('is_patient', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('is_relative', sa.Boolean(), nullable=False))
    op.drop_column('patients', 'passport_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('passport_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('patients', 'is_relative')
    op.drop_column('patients', 'is_patient')
    op.drop_column('patients', 'snils')
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'birthday')
    op.drop_table('relationships')
    op.drop_table('documents')
    # ### end Alembic commands ###
