"""

Revision ID: ed4cc035c329
Revises: 41249e8263b9
Create Date: 2023-08-15 09:38:09.212554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4cc035c329'
down_revision = '41249e8263b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('html', sa.Text(), nullable=True))
    op.drop_column('templates', 'template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('templates', 'html')
    # ### end Alembic commands ###
