"""122

Revision ID: 41249e8263b9
Revises: 8bff9aa1de04
Create Date: 2023-08-14 09:08:01.826235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41249e8263b9'
down_revision = '8bff9aa1de04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('passport_number', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('templates', sa.Column('operator_id', sa.Integer(), nullable=True))
    op.add_column('templates', sa.Column('template', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'templates', 'operators', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'template')
    op.drop_column('templates', 'operator_id')
    op.drop_table('patients')
    op.drop_table('operators')
    # ### end Alembic commands ###
